=== himalayahall/DATA607/Assignment 8/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" />
              <xs:element name="author" type="xs:string" />
              <xs:element name="medium" type="xs:string" />
              <xs:element name="pages" type="xs:unsignedShort" />
              <xs:element name="isbn" type="xs:unsignedLong" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== himalayahall/DATA607/Assignment 8/books_dt.xml
<?xml version="1.0"?>

<root xmlns="https://www.w3schools.com"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="https://raw.githubusercontent.com/himalayahall/DATA607/main/Assignment%208/books.xsd">

		<books:book>
			<books:title>Thinking Fast and Slow</books:title>
			<books:author>Daniel Kahneman</books:author>
			<books:medium>Paperback</books:medium>
			<books:pages>499</books:pages>
			<books:pisbn>0374533555</books:pisbn>
		</books:book>

		<books:book>
			<books:title>Wolf Hall</books:title>
			<books:author>Hilary Mantel</books:author>
			<books:medium>Paperback</books:medium>
			<books:pages>640</books:pages>
			<books:pisbn>1250806712</books:pisbn>
		</books:book>

		<books:book>
			<books:title>Man-Eaters of Kumaon</books:title>
			<books:author>Jim Corbett</books:author>
			<books:medium>Paperback</books:medium>
			<books:pages>184</books:pages>
			<books:pisbn>8129140365</books:pisbn>
		</books:book>		

</root>
